---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-generator
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-generator
    spec:
      containers:
        - image: "dm848/srv-service-generator:v1.1.1"
          imagePullPolicy: Always
          name: service-generator
          ports:
            - containerPort: 5678
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: service-generator
  namespace: "default"
  labels:
    app: service-generator
spec:
  ports:
  - protocol: "TCP"
    port: 5678
    targetPort: 5678
  selector:
    app: service-generator
  type: "ClusterIP"
